# Generated by Django 4.2.2 on 2023-07-31 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarPool',
            fields=[
                ('pool_id', models.IntegerField(primary_key=True, serialize=False)),
                ('from_loc', models.CharField(max_length=100)),
                ('to_loc', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available_seats', models.IntegerField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('write_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarRide',
            fields=[
                ('ride_id', models.IntegerField(primary_key=True, serialize=False)),
                ('from_loc', models.CharField(max_length=100)),
                ('to_loc', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pay_type', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('write_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dob', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('license_no', models.CharField(max_length=100)),
                ('car_year', models.IntegerField()),
                ('car_model', models.CharField()),
                ('car_name', models.CharField(max_length=100)),
                ('car_no', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('write_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pay_type', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver')),
                ('pool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.carpool')),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.carride')),
            ],
        ),
        migrations.CreateModel(
            name='PriceSlab',
            fields=[
                ('slab_id', models.IntegerField(primary_key=True, serialize=False)),
                ('from_km', models.FloatField()),
                ('to_km', models.FloatField()),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=100)),
                ('mode_of_pay', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='DriverLocations',
            fields=[
                ('driver_loc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('locations', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverLastLocUpdate',
            fields=[
                ('driver_update_id', models.IntegerField(primary_key=True, serialize=False)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='rider', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carride',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver'),
        ),
        migrations.AddField(
            model_name='carpool',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver'),
        ),
        migrations.CreateModel(
            name='CarAmenities',
            fields=[
                ('amenities_id', models.IntegerField(primary_key=True, serialize=False)),
                ('features', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver')),
            ],
        ),
    ]
