# Generated by Django 4.2.2 on 2023-06-06 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dob', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('senior_citizen', models.BooleanField()),
                ('id_proof', models.ImageField(upload_to='')),
                ('is_pass', models.BooleanField()),
                ('pass_from_date', models.DateTimeField()),
                ('pass_to_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('write_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
