# Generated by Django 4.2.2 on 2023-08-01 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rideapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carride',
            name='state',
            field=models.CharField(default='draft', max_length=100),
        ),
        migrations.AddField(
            model_name='carride',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carride',
            name='driver_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver'),
        ),
    ]
