# Generated by Django 4.2.2 on 2023-07-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSlab',
            fields=[
                ('slab_id', models.IntegerField(primary_key=True, serialize=False)),
                ('from_km', models.IntegerField()),
                ('to_km', models.IntegerField()),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
