# Generated by Django 4.2.2 on 2023-08-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0002_carride_state_carride_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carride',
            name='ride_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
