# Generated by Django 4.2.2 on 2023-07-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0002_priceslab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceslab',
            name='from_km',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='priceslab',
            name='to_km',
            field=models.FloatField(),
        ),
    ]
