# Generated by Django 4.2.2 on 2023-06-06 07:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0003_driverlocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAmenities',
            fields=[
                ('amenities_id', models.IntegerField(primary_key=True, serialize=False)),
                ('features', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver')),
            ],
        ),
    ]
