# Generated by Django 4.2.2 on 2023-06-06 07:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0004_caramenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRide',
            fields=[
                ('ride_id', models.IntegerField(primary_key=True, serialize=False)),
                ('from_loc', models.CharField(max_length=100)),
                ('to_loc', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pay_type', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='CarPool',
            fields=[
                ('pool_id', models.IntegerField(primary_key=True, serialize=False)),
                ('from_loc', models.CharField(max_length=100)),
                ('to_loc', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available_seats', models.IntegerField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.user')),
            ],
        ),
    ]
