# Generated by Django 4.2.2 on 2023-06-06 07:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0005_carride_carpool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pay_type', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver')),
                ('pool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.carpool')),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.carride')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.user')),
            ],
        ),
    ]
