# Generated by Django 4.2.2 on 2023-06-06 07:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0006_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=100)),
                ('mode_of_pay', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.invoice')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideapp.user')),
            ],
        ),
    ]
