# Generated by Django 4.2.2 on 2023-06-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0007_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpool',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='carride',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
