# Generated by Django 4.2.2 on 2023-06-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0008_remove_carpool_user_id_remove_carride_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_model',
            field=models.CharField(),
        ),
    ]
