# Generated by Django 4.2.2 on 2023-07-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0010_driverlastlocupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.CharField()),
            ],
        ),
    ]
